---
 - name: testing the git
   hosts: localhost
   tasks:
    - name: gitversion
      shell: git --version
      register: gitname
    - name: printing the version
      debug: 
       var: gitname.stdout
         

